=== ebaumann/jphototagger/Plugins/CopyFilenamesToClipboard/src/org/jphototagger/plugin/cftc/help/helpindex.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT helpindex (node|page)*>
<!ELEMENT node (page|title)*>
<!ELEMENT page (title|url)*>
<!ELEMENT url (#PCDATA)>
<!ELEMENT title (#PCDATA)>

=== ebaumann/jphototagger/ImageMetadataViewer/src/de/elmar_baumann/imv/resource/doc/de/contents.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE helpindex SYSTEM 'helpindex.dtd'>
<helpindex>
	<page>
		<url>intro.html</url>
		<title>Was erledigt dieses Programm?</title>
	</page>
	<page>
		<url>fiststeps.html</url>
		<title>Erste Schritte</title>
	</page>
	<page>
		<url>mainwindow.html</url>
		<title>Das Programmfenster</title>
	</page>
	<node>
		<title>Die Auswahl-Kartenreiter</title>
		<page>
			<url>panel_folder.html</url>
			<title>Ordner</title>
		</page>
		<page>
			<url>panel_saved_searches.html</url>
			<title>Suchen</title>
		</page>
		<page>
			<url>panel_collections.html</url>
			<title>Bildsammlungen</title>
		</page>
		<page>
			<url>panel_categories.html</url>
			<title>Kategorien</title>
		</page>
		<page>
			<url>panel_favorite_folders.html</url>
			<title>Favoriten-Ordner</title>
		</page>
	</node>
	<node>
		<title>Die Metadaten-Kartenreiter</title>
		<page>
			<url>panel_iptc.html</url>
			<title>IPTC</title>
		</page>
		<page>
			<url>panel_exif.html</url>
			<title>EXIF</title>
		</page>
		<page>
			<url>panel_xmp.html</url>
			<title>XMP</title>
		</page>
		<page>
			<url>panel_edit.html</url>
			<title>Bearbeiten</title>
		</page>
	</node>
	<node>
		<title>Arbeiten im Bildfenster</title>
		<page>
			<url>action_update_all_metadata.html</url>
			<title>Alle Metadaten aktualisieren</title>
		</page>
		<page>
			<url>action_update_text_metadata.html</url>
			<title>Nur Text-Metadaten aktualisieren</title>
		</page>
		<page>
			<url>action_remove_from_database.html</url>
			<title>Aus der Datenbank entfernen</title>
		</page>
		<page>
			<url>action_replace_xmp.html</url>
			<title>XMP-Daten suchen und ersetzen</title>
		</page>
		<page>
			<url>action_open.html</url>
			<title>Öffnen</title>
		</page>
		<page>
			<url>action_open_with.html</url>
			<title>Öffnen mit</title>
		</page>
		<page>
			<url>action_create_collection.html</url>
			<title>Neue Bildammlung erstellen</title>
		</page>
		<page>
			<url>action_add_to_collection.html</url>
			<title>Einer Bildammlung hinzufügen</title>
		</page>
		<page>
			<url>action_remove_from_collection.html</url>
			<title>Aus der Bildammlung entfernen</title>
		</page>
		<page>
			<url>action_rotate.html</url>
			<title>Vorschaubilder drehen</title>
		</page>
		<page>
			<url>action_filesystem_copy.html</url>
			<title>In ein Verzeichnis kopieren</title>
		</page>
		<page>
			<url>action_filesystem_rename.html</url>
			<title>Auf dem Datenträger umbenennen</title>
		</page>
		<page>
			<url>action_filesystem_move.html</url>
			<title>Auf dem Datenträger verschieben</title>
		</page>
		<page>
			<url>action_filesystem_delete.html</url>
			<title>Vom Datenträger löschen</title>
		</page>
	</node>
	<page>
		<url>advanced_search.html</url>
		<title>Erweiterte Suche</title>
	</page>
	<page>
		<url>action_autocopy_directory.html</url>
		<title>Bilder von der Kameraspeicherkarte einlesen</title>
	</page>
	<node>
		<title>Tipps</title>
		<page>
			<url>tip_use_help.html</url>
			<title>Nutzen Sie die Hilfe</title>
		</page>
		<page>
			<url>tip_check_logfile.html</url>
			<title>Öffnen Sie bei Fehlern die Logdatei</title>
		</page>
		<page>
			<url>tip_use_shortcuts.html</url>
			<title>Tastaturkürzel</title>
		</page>
		<page>
			<url>tip_large_thumbnails.html</url>
			<title>Große Vorschaubilder</title>
		</page>
		<page>
			<url>tip_check_settings.html</url>
			<title>Einstellungen überprüfen</title>
		</page>
		<page>
			<url>tip_save_searches.html</url>
			<title>Suchen speichern</title>
		</page>
		<page>
			<url>tip_refresh_only_textmetadata.html</url>
			<title>Nur Text-Metadaten aktualisieren</title>
		</page>
	</node>
	<node>
		<title>Wichtige Fakten</title>
		<page>
			<url>facts_what_metadata_is_read.html</url>
			<title>Welche Metadaten werden gelesen?</title>
		</page>
		<page>
			<url>facts_what_metadata_is_displayed.html</url>
			<title>Welche Metadaten werden angezeigt?</title>
		</page>
		<page>
			<url>facts_what_metadata_is_in_database.html</url>
			<title>Was ist in der Datenbank gespeichert?</title>
		</page>
		<page>
			<url>facts_count_write_to_database.html</url>
			<title>Wie oft werden Bilder in die Datenbank geschrieben?</title>
		</page>
		<page>
			<url>facts_database_location.html</url>
			<title>Wo ist die Datenbank?</title>
		</page>
		<page>
			<url>facts_why_xmp_sidecarfiles.html</url>
			<title>Warum XMP-Filialdateien?</title>
		</page>
	</node>
	<node>
		<title>Einstellungen-Dialog</title>
		<page>
			<url>settingsdialog_programs.html</url>
			<title>Bilder öffnen</title>
		</page>
		<page>
			<url>settingsdialog_fastsearch.html</url>
			<title>Schnellsuche</title>
		</page>
		<page>
			<url>settingsdialog_thumbnails.html</url>
			<title>Vorschaubilder</title>
		</page>
		<page>
			<url>settingsdialog_iptc.html</url>
			<title>IPTC</title>
		</page>
		<page>
			<url>settingsdialog_tasks.html</url>
			<title>Automatisieren</title>
		</page>
		<page>
			<url>settingsdialog_performance.html</url>
			<title>Leistung</title>
		</page>
		<page>
			<url>settingsdialog_fileexcludepattern.html</url>
			<title>Ausschließen</title>
		</page>
		<page>
			<url>settingsdialog_misc.html</url>
			<title>Sonstiges</title>
		</page>
	</node>
	<node>
		<title>Menübefehle</title>
		<page>
			<url>action_scan_directories.html</url>
			<title>Datei / Verzeichnisse einlesen</title>
		</page>
		<page>
			<url>action_maintain_database.html</url>
			<title>Datei / Datenbank</title>
		</page>
		<page>
			<url>action_autocopy_directory.html</url>
			<title>Datei / Bilder von der Kamera-Speicherkarte kopieren</title>
		</page>
		<page>
			<url>action_edit_settings.html</url>
			<title>Bearbeiten / Einstellungen</title>
		</page>
		<page>
			<url>advanced_search.html</url>
			<title>Bearbeiten / Suchen</title>
		</page>
		<page>
			<url>action_filesystem_rename.html</url>
			<title>Bearbeiten / Auf dem Datenträger umbenennen</title>
		</page>
		<page>
			<url>action_filesystem_delete.html</url>
			<title>Bearbeiten / Vom Datenträger löschen</title>
		</page>
		<page>
			<url>action_iptc_to_xmp.html</url>
			<title>Werkzeuge / IPTC-Daten nach XMP</title>
		</page>
	</node>
</helpindex>
